### ISSUE TITLE
Would you like to provide a mode switch that the user can choose if merge the same word in the dependency graph ?

### ISSUE THREAD

**Issue by zrg1993** [superkerokero/naruhodo#17]
@superkerokero, I am doing the NLP research in Japanese. I really appreciate that naruhodo can store the dependency analysis result into networkx. 

However, I find that even if I only want the dependency graph of one sentence, the same word are merged. I know the merging operation can reduce the scale of the graph when processing multiple sentences at once. However, I want the raw dependency network without merging the same word. 

Would you like to add this mode switch to naruhodo. Or tell me a suggestion about how to do this ?

**Comment by superkerokero** [comment]
In fact, `naruhodo` uses the word itself as the key of the node in the graph, which means it is currently impossible to have the same word in the graph as multiple different nodes.

In order to have multiple nodes for the same word, you need to use something else as the graph keys that are unique for each node(e.g. incremental integers). This can be done by modifying `_addNode` function inside `naruhodo/naruhodo/core/DependencyCoreJa.py`.

**Comment by zrg1993** [comment]
Many thanks to your explanation in detail. I will have a try for that.
