### ISSUE TITLE
On windows OS,  the utils/communication.py  can not read input from stdin.flush().

### ISSUE THREAD

**Issue by zrg1993** [superkerokero/naruhodo#18]
C:\Anaconda3\lib\site-packages\naruhodo\utils\communication.py in query(self, inp)
     43         pattern = r'EOS'
     44         self.proc.stdin.write(inp.encode('utf-8') + six.b('\n'))
---> 45         self.proc.stdin.flush()
     46         result = ""
     47         while True:

OSError: [Errno 22] Invalid argument

I copied the error log. Would you like to help me out? Thank you very much.

**Comment by superkerokero** [comment]
Sorry I don't have windows environment available now, so I can't help you debug this issue.

This library calls executables of `mecab/cabocha` to get the information it needs.
One possible cause of this might be the difference in the names of these executables(i.e. on windows, they might have suffixes like ".exe").

A possible walk-around of this issue is to use docker or some vm software to run linux systems on windows and use `naruhodo` inside linux environment.

**Comment by zrg1993** [comment]
Thanks for your answer, I will try that.
